package phaseflow

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ProjectDocName is the root file that carries the generated spec and phases so
// the agent has one place to refer back to. It is deliberately the same
// PROJECT.md a repo may already use for hand-written conventions: the generated
// content lives inside a delimited block and never disturbs the rest.
const ProjectDocName = "PROJECT.md"

const (
	specBeginMarker = "<!-- gophermind:spec:begin -->"
	specEndMarker   = "<!-- gophermind:spec:end -->"
)

// ProjectDocPath is the absolute path to the project doc under root.
func ProjectDocPath(root string) string { return filepath.Join(root, ProjectDocName) }

// UpsertProjectDoc writes body into the managed block of root's PROJECT.md:
//
//   - markers present -> replace only what is between them
//   - file exists without markers -> append the block, existing bytes untouched
//   - file absent -> create it containing just the block
//
// Regenerating with the same body is idempotent: exactly one block, one copy.
func UpsertProjectDoc(root, body string) error {
	path := ProjectDocPath(root)
	block := specBeginMarker + "\n" + strings.TrimRight(body, "\n") + "\n" + specEndMarker

	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("read %s: %w", ProjectDocName, err)
		}
		return writeFileAtomic(path, block+"\n")
	}

	text := string(existing)
	start := strings.Index(text, specBeginMarker)
	end := strings.Index(text, specEndMarker)
	switch {
	case start >= 0 && end > start:
		text = text[:start] + block + text[end+len(specEndMarker):]
	default:
		// No usable markers (absent, or an end without a begin): append rather
		// than guess, so nothing hand-written is ever lost.
		if !strings.HasSuffix(text, "\n") {
			text += "\n"
		}
		text += "\n" + block + "\n"
	}
	return writeFileAtomic(path, text)
}

// writeFileAtomic writes via a temp file + rename so an interrupted write cannot
// truncate a PROJECT.md that holds hand-written content.
func writeFileAtomic(path, content string) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".project-doc-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // no-op once the rename succeeds
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, 0o644); err != nil {
		return err
	}
	return os.Rename(name, path)
}

// RenderProjectDocBody renders the spec overview and every phase's tasks with
// their current status, so PROJECT.md reflects the plan as execution advances.
func RenderProjectDocBody(name, overview string, a *Assignments) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — generated project spec\n\n", name)
	b.WriteString("Generated by `/project`. Edit the plan through the flow, not by hand:\n")
	b.WriteString("this block is regenerated after planning and after every execute run.\n\n")

	if strings.TrimSpace(overview) != "" {
		b.WriteString("## Overview\n\n")
		b.WriteString(strings.TrimSpace(overview))
		b.WriteString("\n\n")
	}

	if a == nil || len(a.Tasks) == 0 {
		b.WriteString("## Phases\n\nNo tasks planned yet.\n")
		return b.String()
	}

	// Group tasks by phase, keeping phases and tasks in ascending order.
	byPhase := map[string][]Task{}
	for _, t := range a.Tasks {
		byPhase[t.Phase] = append(byPhase[t.Phase], t)
	}
	phases := make([]string, 0, len(byPhase))
	for p := range byPhase {
		phases = append(phases, p)
	}
	sort.Strings(phases)

	b.WriteString("## Phases\n")
	for _, p := range phases {
		tasks := byPhase[p]
		sort.Slice(tasks, func(i, j int) bool { return tasks[i].ID < tasks[j].ID })
		fmt.Fprintf(&b, "\n### Phase %s\n\n", p)
		b.WriteString("| Task | Title | Status |\n|---|---|---|\n")
		for _, t := range tasks {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", t.ID, t.Title, t.Status)
		}
	}
	return b.String()
}
